# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

#pool:
#  vmImage: ubuntu-latest

pool:
  name: Azure-Infra_Pool

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  condition: 
- task: Docker@2
  inputs:
    containerRegistry: 'acr-connection'
    command: 'login'

- script: echo Hello, world!
    git clone https://github.com/santoshi0712/devopsrbapoc.git

- task: Docker@2
  inputs:
    containerRegistry: acr-connection
    repository: '$(Build.Repository.Name)'
    command: 'build'
    Dockerfile: 'dockerfile1'
    arguments: '--disable-content-trust=false''
    tags:  $(Build.BuildId)

- task: Docker@2
  inputs:
    command: push
    containerRegistry: jfrogrepo
    repository: dockerimages/$(Build.Repository.Name)
    tags: $(Build.BuildId)
